.github/workflows/build-test.yml
client.go
generate/generate.go
lib.go
paths.go
types.go

This commit removes all naming customisations as we will be editing Operation Ids directly on the spec from now on.
This is the first part of a larger refactoring effort.

Refactor naming customisations

---

internal/generate/test_utils/oneof-test
internal/generate/types.go
internal/generate/types_test.go

Extracts code into smaller functions and removes the amount of places where code is printed out

Continue to restructure types generation

---

go.mod
go.sum
internal/generate/responses.go
internal/generate/types.go
internal/generate/types_test.go

Start constructing `[]TypeTemplate` to use instead of writing to file from several places, or saving the entire file in a string variable.
Done:

Populate `TypeTemplate` structs

---

internal/generate/types.go
internal/generate/types_test.go

Construct []TypeTemplate to use instead of writing to file from several places, or saving the entire file in a string variable for OneOf.

Populate TypeTemplates with OneOf

---

internal/generate/responses.go
internal/generate/types.go
internal/generate/types_test.go

Construct []TypeTemplate and []EnumTemplate to use instead of writing to file from several places, or saving the entire file in a string variable for enums.

Populate template structs for enums

---

internal/generate/paths.go
internal/generate/templates/test.tpl
internal/generate/test_utils/tpl_test

This commit modifies the paths.go generation functions to only write to file from a single place. Eventually templates will be used instead of forming the structure with several `fmt.Printf()`, a small testing function for this was added.
Additionally, the `writeMethod()` function has been separated into two to begin the work of having different functions for methods if necessary.

Beginning of path gen refactor

---

internal/generate/paths.go
internal/generate/paths_test.go
internal/generate/templates/description.tpl
internal/generate/templates/listall_method.tpl
internal/generate/templates/no_resptype_body_method.tpl
internal/generate/templates/no_resptype_method.tpl
internal/generate/templates/resptype_body_method.tpl
internal/generate/templates/resptype_method.tpl
internal/generate/test_utils/paths_output
internal/generate/test_utils/paths_output_expected
oxide/paths.go

Switches code to use templates instead of printlines to generate methods.
Removes unused code and function refactor

Use templates to generate methods

---

internal/generate/test_utils/types_output
internal/generate/test_utils/types_output_expected
internal/generate/types.go
internal/generate/types_test.go
oxide/types.go

Closes: https://github.com/oxidecomputer/oxide.go/issues/74
This commit uses generated types instead of strings for enums in generated struct types

Handle enum types within structs

---

internal/generate/types.go
internal/generate/types_test.go
oxide/types.go

For now these values are treated as interfaces. This way you can pass whichever
of the struct types you need like this:
```go
ipRange := oxide.Ipv4Range{
First: "172.20.15.240",
Last:  "172.20.15.250",
}
body := oxide.IpRange(ipRange)
resp, _ := client.IpPoolRangeAdd("mypool", &body)
```
Probably not the best approach, but will leave them this way until I come up with
a more idiomatic solution. Keep an eye out on this one to refine.
Closes: https://github.com/oxidecomputer/oxide.go/issues/72

Handle nested allOf references types within oneOfs

---

oxide/validate.go
oxide/validate_test.go

Related: https://github.com/oxidecomputer/oxide.go/issues/37
With this implementation of a validator there are a few ways to go on about validating the methods:
Directly inside the client methods. The end user doesn't have to worry about thinking about validation
```go
// Generated code
func (c *Client) ProjectCreate(params ProjectCreateParams) (*Project, error) {
v := new(Validator)
v.HasRequiredObj(params.Body)
v.HasRequiredStr(params.SomeString)
// Add more checks if necessary
if !v.IsValid() {
return nil, fmt.Errorf("validation error: %v", v.Error())
}
<...>
```
Into custom validators for each params type. We can choose to integrate the validation methods into the client methods or have the end users decide to use the validators or not.
```go
// Generated code
type ProjectCreateParams …
```

Initial validator implementation

---

README.md
internal/generate/templates/listall_method.tpl
internal/generate/templates/no_resptype_body_method.tpl
internal/generate/templates/no_resptype_method.tpl
internal/generate/templates/resptype_body_method.tpl
internal/generate/templates/resptype_method.tpl
internal/generate/test_utils/paths_output
internal/generate/test_utils/paths_output_expected
oxide/lib.go
oxide/lib_test.go
oxide/paths.go

Previously, the Oxide GO SDK generated functions that did not take a
`context.Context`. That means callers were unable to specify any
cancellation or timeout logic when using this SDK.
This SDK has been updated to generate functions that take
`context.Context` as their first argument, which is a common Go idiom
when working with `context.Context`.
Since function signatures have been modified this is a breaking change!
Here's an example of how a client would use this updated Go SDK:
```go
package main
import (
"fmt"
"github.com/oxidecomputer/oxide.go/oxide"
)
func main() {
client, err := oxide.NewClient("<auth token>", "<user-agent>", "<host>")
if err != nil {
panic(err)
}
ctx := context.Background()
params := oxide.ProjectCreateParams{
Body: &oxide.ProjectCreate{
Description: "A sample …
```

oxide: support specifying a context.Context

---

internal/generate/templates/no_resptype_body_method.tpl
internal/generate/templates/no_resptype_method.tpl
internal/generate/templates/resptype_body_method.tpl
internal/generate/templates/resptype_method.tpl
internal/generate/test_utils/paths_output
internal/generate/test_utils/paths_output_expected
oxide/errors.go
oxide/errors_test.go
oxide/paths.go

The `HTTPError` type has been modified to include the HTTP response and the API's `ErrorResponse` type. 
```go
type HTTPError struct {
// ErrorResponse is the API's Error response type.
ErrorResponse *ErrorResponse
// HTTPResponse is the raw HTTP response returned by the server.
HTTPResponse *http.Response
// RawBody is the raw response body returned by the server.
RawBody string
}
```
Additionally, the formatting for the `Error()` method has been enhanced to provide more information about the error in this manner:
```console
api error: POST https://oxide.sys.rack2.eng.oxide.computer/v1/projects
----------- RESPONSE -----------
Status: 400 ObjectAlreadyExists
Message: already exists: project "my-project"
RequestID: 580a1c02-a624-4931-83e8-01133a21acd9
------- RESPONSE HEADERS ------- …
```

Improved error handling with HTTPError type

---

go.mod

Closes: https://github.com/oxidecomputer/oxide.go/issues/146
We would like to start with a clean slate with version v0.1.0-beta1. These previous versions were published prematurely

Retract unecessary versions

---

.changelog/v0.1.0-beta2.toml
.github/workflows/build-test.yml
.gitignore
Makefile
oxide/utils_test.go

- Make target for creating a changelog
- Makefile will no longer download tooling every single time you call a target, and various fixes
Closes: https://github.com/oxidecomputer/oxide.go/issues/147

Implement changelog automation and makefile clean up

---

.changelog/v0.1.0-beta2.toml
internal/generate/exceptions.go
internal/generate/types.go
internal/generate/utils.go
oxide/types.go

Remove `omitempty` from the rules in `VpcFirewallRuleUpdateParams` to be able to delete all firewall rules

Fix VPC firewall rules delete action

---

.changelog/v0.1.0-beta3.toml
.github/ISSUE_TEMPLATE/release_checklist.md
CONTRIBUTING.md
README.md
internal/generate/templates/no_resptype_body_method.tpl
internal/generate/templates/no_resptype_method.tpl
internal/generate/templates/resptype_body_method.tpl
internal/generate/templates/resptype_method.tpl
internal/generate/test_utils/paths_output
internal/generate/test_utils/paths_output_expected
oxide/lib.go
oxide/lib_test.go
oxide/paths.go
oxide/version.go

Previously, there were two exported functions to create an Oxide API
client.
- `func NewClient(token, userAgent, host string) (*Client, error)`
- `func NewClientFromEnv(userAgent string) (*Client, error)`
These two functions required a user agent to be passed as an argument,
which should be an optional argument instead. Additionally, having two
separate functions means a user must switch functions when they wish to
switch to or from using an environment to configure the client.
The code always created a custom `http.RoundTripper` to be used as the
transport for the underlying HTTP client. The only function of this
custom tranport was to add HTTP headers to the request.
This patch updates the SDK to export a single function to create an
Oxide API client.
- `func NewClient(cfg *Config) …

oxide: refactor exported client API

---

Makefile

Users may not be using `/bin/bash` as their preferred shell. This is common on macOS, where Bash is commonly installed from Homebrew.
Update `SHELL` to use `/usr/bin/env` and set `-eo pipefail` to force jobs to exit on failure immediately.

Don't hardcode Bash path in Makefile

---

.changelog/v0.1.0-beta9.toml
internal/generate/types.go
internal/generate/utils.go
oxide/types.go
oxide/utils.go

Our OpenAPI spec defines maps in the following manner:
```json
"Silo": {
"description": "View of a Silo\n\nA Silo is the highest level unit of isolation.",
"type": "object",
"properties": {
"mapped_fleet_roles": {
"description": "Mapping of which Fleet roles are conferred by each Silo role\n\nThe default is that no Fleet roles are conferred by any Silo roles unless there's a corresponding entry in this map.",
"type": "object",
"additionalProperties": {
"type": "array",
"items": {
"$ref": "#/components/schemas/FleetRole"
},
"uniqueItems": true
}
}
},
"required": [
"mapped_fleet_roles",
]
}
```
In this scenario this should be parsed into
```go
type Silo struct {
// MappedFleetRoles is mapping of which Fleet roles are conferred by each Silo role
//
// The default is that no Fleet roles are …
```

Account for additional fields "array" types that don't specify map keys

---

internal/generate/paths.go
internal/generate/test_utils/types_output
internal/generate/test_utils/types_output_expected
internal/generate/types.go
oxide/paths.go
oxide/types.go

The OpenAPI spec concatenates some multi-line doc comments in the original Rust code into a single long line. We write these long lines verbatim into the Go source we generate, and some are sufficiently long that viewing the full comment requires [scrolling sideways on pkg.go.dev](https://pkg.go.dev/github.com/oxidecomputer/oxide.go@v0.1.0-beta9/oxide#InternetGatewayCreate).
Add a helper function to split long doc strings into lines of roughly 100 characters and apply it to the `Description` of our generated paths and types.
Closes #248

Split long doc strings over multiple lines

---

.changelog/v0.4.0.toml
internal/generate/paths.go
internal/generate/templates/listall_method.tpl
internal/generate/test_utils/paths_output
internal/generate/test_utils/paths_output_expected
internal/generate/types.go
internal/generate/utils.go
oxide/paths.go
oxide/types.go
oxide/utils.go
oxide/validate.go
oxide/validate_test.go

I've additionally manually tested by updating the terraform provider locally and running all acceptance tests and with the following terraform config:
```hcl
terraform {
required_version = ">= 1.0"
required_providers {
oxide = {
source  = "oxidecomputer/oxide"
version = "0.8.0-dev"
}
}
}
resource "oxide_vpc_firewall_rules" "talos_k8s_nodeports" {
vpc_id = "8c2757bc-1cea-422c-ba66-e330bfbcaf92"
rules = [
{
name        = "talos-k8s-nodeports"
description = "Talos Kubernetes node ports."
action      = "allow"
direction   = "inbound"
priority    = 0
status      = "enabled"
filters = {
ports     = ["30000-32767"]
protocols = ["TCP"]
},
targets = [
{
type  = "vpc"
value = "dud"
}
]
}
]
}
```
```console
$ terraform apply
<...>
Terraform used the selected providers to generate the following …
```

Set integer fields as pointers

---

.changelog/v0.5.0.toml
internal/generate/exceptions.go
internal/generate/types.go
internal/generate/utils.go
oxide/types.go

I think this should fix https://github.com/oxidecomputer/oxide.go/issues/282
I'm a little concerned about any repercussions with `VpcFirewallRuleFilter` WDYT @sudomateo ?

Handle nullable arrays

---

.changelog/v0.5.0.toml
.github/workflows/build-test.yml
.github/workflows/generate.yml
.github/workflows/make-release.yml
Makefile
go.mod

Update to Go 1.24. Also, update the dependencies to be compatible with Go 1.24.

go: update to 1.24

---

.changelog/v0.5.0.toml
internal/generate/exceptions.go
internal/generate/types.go
oxide/types.go

Set `omitzero` on the following types to allow clients to set an empty slice and have it serialized to `[]`, which is required by Oxide APIs to unset a value.
* `[]VpcFirewallRuleUpdate`
* `[]NameOrId`
The previous behavior would omit an empty slice entirely during serialization, causing the Oxide APIs to respond with an error.

generate: set omitzero on specific types

---

.github/CODEOWNERS

misc: add codeowners

---

internal/generate/main.go
oxide/types.go

For local testing, we may want to generate the sdk from a local spec file, rather than pulling from github. This patch adds an environment variable override to optionally source the spec from a local file instead.

oxide: optionally build from local openapi spec.

---

.github/workflows/build-test.yml

Updated the workflow to trigger on all push events and not pull request events so that push events on branches by the generate workflow will trigger CI/CD and not hang the pull request for review.
Related to https://github.com/oxidecomputer/oxide.go/issues/292.

ci/cd: trigger on all push events

---

internal/generate/types.go
internal/generate/utils.go
oxide/types.go

When an openapi field includes an `additionalProperties` key, it represents a map to the type specified in the schema reference. We already correctly handle the special case of mapping a string to a slice of the referenced type as a `map[string][]type`, but not the case where the nested type isn't a slice. This patch adds logic for the missing `map[string[type` case.

generate: handle map[string]any types correctly.
